// vue_colour_palette_picker/src/components/PageLayout.vue
<template>
  <!-- links to the page where users choose random or custom colour palette -->
  <router-link to="/colour-palette-generator">
    <div class="header">
      <img src="../assets/starfluffy_logo.png" class="icon-logo" />
      <p class="site-name">Starfluffy Colour Palette Generator</p>
    </div>
  </router-link>
  <router-view></router-view>
</template>

// frontend/src/components/PageLayout.jsx
import { Link, Outlet } from "react-router-dom";
import logo from "../assets/starfluffy_logo.png";

export default function PageLayout() {
  return (
    <>
      {/* links to the page where users choose random or custom colour palette */}
      <Link to="/colour-palette-generator">
        <div className="header">
          <img src={logo} className="icon-logo" />
          <p className="site-name">Starfluffy Colour Palette Generator</p>
        </div>
      </Link>
      <Outlet />
    </>
  );
}
