// vue_colour_palette_picker/src/components/ModesPage.vue
<script setup>
import { inject } from "vue";

const data = inject("data");
const inputName = inject("inputName");

// sets the input for the api back to the default
function setDefault() {
  data.value = { model: "default" };
  inputName.value = "Random";
}

// imports the images from the assets folder and returns the url for the image
function getImageUrl(name) {
  return new URL(`../assets/${name}`, import.meta.url).href;
}
</script>

<template>
  <!-- centres the contents and displays them as flex items -->
  <div class="centre flex">
    <!-- button that links to page where user can select a style -->
    <router-link to="/colour-palette-generator/choose-style">
      <button
        class="choose-button"
        @click="setDefault"
        :style="{
          backgroundImage: `url(${getImageUrl('choose-colours.png')})`,
        }"
      >
        Let me choose a style for my colour palette!
      </button>
    </router-link>

    <!-- button that links to the colour palette generated page with a random palete generated -->
    <router-link to="/colour-palette-generator/generate">
      <button
        class="choose-button"
        @click="setDefault"
        :style="{
          backgroundImage: `url(${getImageUrl('random-colours.png')})`,
        }"
      >
        Just give me a random colour palette!
      </button>
    </router-link>
  </div>
</template>

// react_colour_palette_picker/src/components/ModesPage.jsx
import { useContext } from "react";
import { AppContext } from "../AppContextProvider";
import { Link } from "react-router-dom";
import chooseImage from "../assets/choose-colours.png";
import randomColoursImage from "../assets/random-colours.png";

export default function ModesPage() {
  const { data, inputName, setData, setInputName } = useContext(AppContext);

  // sets the input for the api back to the default
  function setDefault() {
    setData({ model: "default" });
    setInputName("Random");
  }

  return (
    // centres the contents and displays them as flex items
    <div className="centre flex">
      {/* button that links to page where user can select a style */}
      <Link to="/colour-palette-generator/choose-style">
        <button
          className="choose-button"
          onClick={() => setDefault()}
          style={{backgroundImage: `url(${chooseImage})` }}
        >
          Let me choose a style for my colour palette!
        </button>
      </Link>

      {/* button that links to the colour palette generated page with a random palete generated */}
      <Link to="/colour-palette-generator/generate">
        <button
          className="choose-button"
          onClick={() => setDefault()}
          style={{backgroundImage: `url(${randomColoursImage})` }}
        >
          Just give me a random colour palette!
        </button>
      </Link>
    </div>
  );
}
